-- MEMBER 테이블 관련 쿼리문들
-- 1. 로그인용 쿼리문
SELECT *
  FROM MEMBER
 WHERE MEMBER_ID = ?
   AND STATUS = 'Y' 
   
-- 2. 회원가입용 쿼리문
INSERT INTO MEMBER(MEMBER_NO
                 , MEMBER_ID
                 , MEMBER_PWD
                 , MEMBER_NAME
                 , BIRTH_DATE
                 , PHONE
                 , EMAIL
                 , SIGNUP_DATE
                 , ADDRESS)
            VALUES(MEMBER_SEQ.NEXTVAL
                 , ?
                 , ?
                 , ?
                 , ?
                 , ?
                 , ?
                 , ?
                 , ?)
                 
-- 3. 아이디 중복체크용 쿼리문
SELECT COUNT(*)
  FROM MEMBER
 WHERE MEMBER_ID = ?
 
-- 4. 이메일 인증번호 발급용 쿼리문
INSERT INTO IDENTIFICATION(EMAIL,
                         , AUTH_CODE
                         , AUTH_CODE_DATE)
                    VALUES(?
                         , ?
                         , SYSDATE)
                         
-- 5. 이메일 인증번호 대조용 쿼리문
SELECT AUTH_CODE
  FROM IDENTIFICATION
 WHERE EMAIL = ?
   AND AUTH_CODE = ?
   AND SYSDATE < TO_DATE(AUTH_CODE_DATE, 'YYYY-MM-DD HH24:MI:SS') + NUMTODSINTERVAL(3, 'MINUTE');

-- 6. 이메일 인증번호 삭제용 쿼리문
DELETE
  FROM IDENTIFICATION
 WHERE EMAIL = ?
 
-- 7. 아이디 찾기용 쿼리문
SELECT MEMBER_ID
  FROM MEMBER
 WHERE MEMBER_NAME = ?
   AND EMAIL = ?
   AND STATUS = 'Y'
  
-- 8. 비밀번호 찾기용 쿼리문
SELECT *
  FROM MEMBER
 WHERE MEMBER_NAME = ?
   AND MEMBER_ID = ?
   AND EMAIL = ?
   AND STATUS = 'Y'
   
-- 9. 비밀번호 변경용 쿼리문
UPDATE MEMBER
   SET MEMBER_PWD = ?
 WHERE MEMBER_NAME = ?
   AND MEMBER_ID = ?
   AND EMAIL = ?
   AND STATUS = 'Y'
  
-- 10. 회원탈퇴용 쿼리문
UPDATE MEMBER
   SET STATUS = 'N'
 WHERE MEMBER_ID = ?
   AND STATUS = 'Y';
   
   
-- 예약 관련 쿼리문들
-- 1. 
   
       
                 
-- 캠핑장 더미데이터 생성 구문
-- 1. SECTION 테이블
INSERT INTO SECTION
             VALUES('A', '캠핑카존');
INSERT INTO SECTION
             VALUES('B', '글램핑존');
INSERT INTO SECTION
             VALUES('C', '일반석');
INSERT INTO SECTION
             VALUES('D', '바베큐장');
             
-- 2. CAMPSITE 테이블
INSERT INTO CAMPSITE
            VALUES(CAMP_SEQ.NEXTVAL, 1, 30000, 'A');
INSERT INTO CAMPSITE
            VALUES(CAMP_SEQ.NEXTVAL, 2, 30000, 'A');
INSERT INTO CAMPSITE
            VALUES(CAMP_SEQ.NEXTVAL, 3, 30000, 'A');
INSERT INTO CAMPSITE
            VALUES(CAMP_SEQ.NEXTVAL, 4, 30000, 'A');
INSERT INTO CAMPSITE
            VALUES(CAMP_SEQ.NEXTVAL, 5, 30000, 'A');
INSERT INTO CAMPSITE
            VALUES(CAMP_SEQ.NEXTVAL, 6, 30000, 'A');
INSERT INTO CAMPSITE
            VALUES(CAMP_SEQ.NEXTVAL, 7, 30000, 'A');
INSERT INTO CAMPSITE
            VALUES(CAMP_SEQ.NEXTVAL, 8, 30000, 'A');
INSERT INTO CAMPSITE
            VALUES(CAMP_SEQ.NEXTVAL, 9, 30000, 'A');
INSERT INTO CAMPSITE
            VALUES(CAMP_SEQ.NEXTVAL, 10, 30000, 'A');

INSERT INTO CAMPSITE
            VALUES(CAMP_SEQ.NEXTVAL, 1, 40000, 'B');
INSERT INTO CAMPSITE
            VALUES(CAMP_SEQ.NEXTVAL, 2, 40000, 'B');
INSERT INTO CAMPSITE
            VALUES(CAMP_SEQ.NEXTVAL, 3, 40000, 'B');
INSERT INTO CAMPSITE
            VALUES(CAMP_SEQ.NEXTVAL, 4, 40000, 'B');
INSERT INTO CAMPSITE
            VALUES(CAMP_SEQ.NEXTVAL, 5, 40000, 'B');
INSERT INTO CAMPSITE
            VALUES(CAMP_SEQ.NEXTVAL, 6, 40000, 'B');
INSERT INTO CAMPSITE
            VALUES(CAMP_SEQ.NEXTVAL, 7, 40000, 'B');
INSERT INTO CAMPSITE
            VALUES(CAMP_SEQ.NEXTVAL, 8, 40000, 'B');
INSERT INTO CAMPSITE
            VALUES(CAMP_SEQ.NEXTVAL, 9, 40000, 'B');
INSERT INTO CAMPSITE
            VALUES(CAMP_SEQ.NEXTVAL, 10, 40000, 'B');

INSERT INTO CAMPSITE
            VALUES(CAMP_SEQ.NEXTVAL, 1, 50000, 'C');
INSERT INTO CAMPSITE
            VALUES(CAMP_SEQ.NEXTVAL, 2, 50000, 'C');
INSERT INTO CAMPSITE
            VALUES(CAMP_SEQ.NEXTVAL, 3, 50000, 'C');
INSERT INTO CAMPSITE
            VALUES(CAMP_SEQ.NEXTVAL, 4, 50000, 'C');
INSERT INTO CAMPSITE
            VALUES(CAMP_SEQ.NEXTVAL, 5, 50000, 'C');
INSERT INTO CAMPSITE
            VALUES(CAMP_SEQ.NEXTVAL, 6, 50000, 'C');
INSERT INTO CAMPSITE
            VALUES(CAMP_SEQ.NEXTVAL, 7, 50000, 'C');
INSERT INTO CAMPSITE
            VALUES(CAMP_SEQ.NEXTVAL, 8, 50000, 'C');
INSERT INTO CAMPSITE
            VALUES(CAMP_SEQ.NEXTVAL, 9, 50000, 'C');
INSERT INTO CAMPSITE
            VALUES(CAMP_SEQ.NEXTVAL, 10, 50000, 'C');

INSERT INTO CAMPSITE
            VALUES(CAMP_SEQ.NEXTVAL, 1, 60000, 'D');
INSERT INTO CAMPSITE
            VALUES(CAMP_SEQ.NEXTVAL, 2, 60000, 'D');
INSERT INTO CAMPSITE
            VALUES(CAMP_SEQ.NEXTVAL, 3, 60000, 'D');
INSERT INTO CAMPSITE
            VALUES(CAMP_SEQ.NEXTVAL, 4, 60000, 'D');
INSERT INTO CAMPSITE
            VALUES(CAMP_SEQ.NEXTVAL, 5, 60000, 'D');
INSERT INTO CAMPSITE
            VALUES(CAMP_SEQ.NEXTVAL, 6, 60000, 'D');
INSERT INTO CAMPSITE
            VALUES(CAMP_SEQ.NEXTVAL, 7, 60000, 'D');
INSERT INTO CAMPSITE
            VALUES(CAMP_SEQ.NEXTVAL, 8, 60000, 'D');
INSERT INTO CAMPSITE
            VALUES(CAMP_SEQ.NEXTVAL, 9, 60000, 'D');
INSERT INTO CAMPSITE
            VALUES(CAMP_SEQ.NEXTVAL, 10, 60000, 'D');
  
COMMIT;
  
  
  
  
  
  
  